### ISSUE TITLE
HiddenServiceOnionBalanceInstance error

### ISSUE THREAD

**Issue by BobJimmbob11** [torproject/onionbalance#29]
I followed the Onion V3 guide and i get this error when i add "HiddenServiceOnionBalanceInstance 1" in my torrc backend server.
Error Log
host systemd[1]: Starting Anonymizing overlay network for TCP...
host tor[]: [notice] Tor 0.4.3.4-rc running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
host tor[]: [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
 host tor[]:  [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
host tor[]:  [notice] Read configuration file "/etc/tor/torrc".
 host tor[]: May 09 15:40:56.117 [notice] Included configuration file or directory at recursion level 2: "/usr/local/etc/torrc.d/".
host tor[]: [notice] Included configuration file or directory at recursion level 1: "/etc/torrc.d/".
host tor[]: [warn] Failed to parse/validate config: Unknown option 'HiddenServiceOnionBalanceInstance'.  Failing.
 host tor[]:  [err] Reading config failed--see warnings above.
host systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
host systemd[1]: tor@default.service: Failed with result 'exit-code'.
host systemd[1]: Failed to start Anonymizing overlay network for TCP.
 host systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
host systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
host systemd[1]: Stopped Anonymizing overlay network for TCP.
host systemd[1]: tor@default.service: Start request repeated too quickly.
host systemd[1]: tor@default.service: Failed with result 'exit-code'.
 host systemd[1]: Failed to start Anonymizing overlay network for TCP.

**Comment by asn-d6** [comment]
Hello, that's because you didn't use the latest git master of Tor as specified [in the docs](https://onionbalance.readthedocs.io/en/latest/v3/tutorial-v3.html#step-3-configuring-the-backend-instances). Basically, the Tor version you tried (`0.4.3.4`) does not support the `HiddenServiceOnionBalanceInstance` feature. You will need a Tor running `0.4.4.x` which you can get using git master.

Best of luck. I'm closing this ticket but feel free to reopen it if you have more questions, or I said something wrong!
